use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Lang {
    pub code: String,
    pub name: String,

    // Main menu
    pub menu_install_version: String,
    pub menu_install_mod_loader: String,
    pub menu_launch_game: String,
    pub menu_launch_preset: String,
    pub menu_manage_presets: String,
    pub menu_manage_accounts: String,
    pub menu_manage_textures: String,
    pub menu_manage_shaders: String,
    pub menu_manage_instances: String,
    pub menu_manage_mods: String,
    pub menu_check_mod_updates: String,
    pub menu_manage_skins: String,
    pub menu_manage_worlds: String,
    pub menu_screenshot_gallery: String,
    pub menu_view_installed: String,
    pub menu_launch_history: String,
    pub menu_news: String,
    pub menu_exit: String,

    // Common
    pub back: String,
    pub yes: String,
    pub no: String,
    pub confirm: String,
    pub select_account: String,
    pub select_version: String,
    pub username: String,
    pub password: String,
    pub goodbye: String,

    // Status
    pub fetching_manifest: String,
    pub downloading_jar: String,
    pub downloading_libs: String,
    pub downloading_assets: String,
    pub verifying_assets: String,
    pub validating_session: String,
    pub session_expired: String,
    pub session_refreshing: String,
    pub installed_ok: String,
    pub game_exited: String,

    // Account manager
    pub add_local_profile: String,
    pub rename_local_profile: String,
    pub remove_local_profile: String,
    pub login_microsoft: String,
    pub refresh_microsoft: String,
    pub remove_microsoft: String,
    pub uuid_type_prompt: String,
    pub uuid_offline: String,
    pub uuid_random: String,

    // World manager
    pub worlds_title: String,
    pub rename_world: String,
    pub delete_world: String,
    pub export_world: String,
    pub open_saves_folder: String,
    pub world_new_name: String,
    pub world_delete_confirm: String,
    pub world_export_path: String,

    // Errors / warnings
    pub no_versions_installed: String,
    pub no_accounts_configured: String,
    pub skin_requires_microsoft: String,
    pub low_ram_warning: String,
}

impl Lang {
    pub fn english() -> Self {
        Self {
            code: "en".into(), name: "English".into(),
            menu_install_version: "Install Version".into(),
            menu_install_mod_loader: "Install Mod Loader".into(),
            menu_launch_game: "Launch Game".into(),
            menu_launch_preset: "Launch Preset".into(),
            menu_manage_presets: "Manage Presets".into(),
            menu_manage_accounts: "Manage Accounts".into(),
            menu_manage_textures: "Manage Textures".into(),
            menu_manage_shaders: "Manage Shaders".into(),
            menu_manage_instances: "Manage Instances".into(),
            menu_manage_mods: "Manage Mods".into(),
            menu_check_mod_updates: "Check Mod Updates".into(),
            menu_manage_skins: "Manage Skins".into(),
            menu_manage_worlds: "Manage Worlds".into(),
            menu_screenshot_gallery: "Screenshot Gallery".into(),
            menu_view_installed: "View Installed Versions".into(),
            menu_launch_history: "Launch History".into(),
            menu_news: "News".into(),
            menu_exit: "Exit".into(),
            back: "Back".into(),
            yes: "Yes".into(),
            no: "No".into(),
            confirm: "Confirm".into(),
            select_account: "Select account".into(),
            select_version: "Select version".into(),
            username: "Username".into(),
            password: "Password".into(),
            goodbye: "Goodbye.".into(),
            fetching_manifest: "Fetching version manifest...".into(),
            downloading_jar: "Downloading client JAR...".into(),
            downloading_libs: "Downloading libraries...".into(),
            downloading_assets: "Downloading assets...".into(),
            verifying_assets: "Verifying assets...".into(),
            validating_session: "Validating session...".into(),
            session_expired: "expired".into(),
            session_refreshing: "Token expired — refreshing...".into(),
            installed_ok: "installed successfully!".into(),
            game_exited: "Game exited with status:".into(),
            add_local_profile: "Add local profile".into(),
            rename_local_profile: "Rename local profile".into(),
            remove_local_profile: "Remove local profile".into(),
            login_microsoft: "Log in with Microsoft (add account)".into(),
            refresh_microsoft: "Refresh Microsoft token".into(),
            remove_microsoft: "Remove Microsoft account".into(),
            uuid_type_prompt: "UUID type".into(),
            uuid_offline: "Offline (deterministic, based on username)".into(),
            uuid_random: "Random (new UUID each time)".into(),
            worlds_title: "Worlds".into(),
            rename_world: "Rename world".into(),
            delete_world: "Delete world".into(),
            export_world: "Export world (zip)".into(),
            open_saves_folder: "Open saves folder".into(),
            world_new_name: "New name".into(),
            world_delete_confirm: "Permanently delete".into(),
            world_export_path: "Save zip to path".into(),
            no_versions_installed: "No versions installed. Please install a version first.".into(),
            no_accounts_configured: "No accounts configured.".into(),
            skin_requires_microsoft: "Skin management requires a Microsoft account.".into(),
            low_ram_warning: "Low RAM: profile needs {}MB but only {}MB is free.".into(),
        }
    }

    pub fn spanish() -> Self {
        Self {
            code: "es".into(), name: "Español".into(),
            menu_install_version: "Instalar versión".into(),
            menu_install_mod_loader: "Instalar cargador de mods".into(),
            menu_launch_game: "Iniciar juego".into(),
            menu_launch_preset: "Iniciar perfil".into(),
            menu_manage_presets: "Gestionar perfiles".into(),
            menu_manage_accounts: "Gestionar cuentas".into(),
            menu_manage_textures: "Gestionar texturas".into(),
            menu_manage_shaders: "Gestionar shaders".into(),
            menu_manage_instances: "Gestionar instancias".into(),
            menu_manage_mods: "Gestionar mods".into(),
            menu_check_mod_updates: "Buscar actualizaciones de mods".into(),
            menu_manage_skins: "Gestionar skins".into(),
            menu_manage_worlds: "Gestionar mundos".into(),
            menu_screenshot_gallery: "Galería de capturas".into(),
            menu_view_installed: "Ver versiones instaladas".into(),
            menu_launch_history: "Historial de lanzamientos".into(),
            menu_news: "Noticias".into(),
            menu_exit: "Salir".into(),
            back: "Volver".into(),
            yes: "Sí".into(),
            no: "No".into(),
            confirm: "Confirmar".into(),
            select_account: "Seleccionar cuenta".into(),
            select_version: "Seleccionar versión".into(),
            username: "Nombre de usuario".into(),
            password: "Contraseña".into(),
            goodbye: "Hasta luego.".into(),
            fetching_manifest: "Obteniendo manifiesto de versiones...".into(),
            downloading_jar: "Descargando JAR del cliente...".into(),
            downloading_libs: "Descargando bibliotecas...".into(),
            downloading_assets: "Descargando recursos...".into(),
            verifying_assets: "Verificando recursos...".into(),
            validating_session: "Validando sesión...".into(),
            session_expired: "expirada".into(),
            session_refreshing: "Token expirado — actualizando...".into(),
            installed_ok: "¡instalado correctamente!".into(),
            game_exited: "El juego terminó con estado:".into(),
            add_local_profile: "Añadir perfil local".into(),
            rename_local_profile: "Renombrar perfil local".into(),
            remove_local_profile: "Eliminar perfil local".into(),
            login_microsoft: "Iniciar sesión con Microsoft".into(),
            refresh_microsoft: "Actualizar token de Microsoft".into(),
            remove_microsoft: "Eliminar cuenta de Microsoft".into(),
            uuid_type_prompt: "Tipo de UUID".into(),
            uuid_offline: "Offline (determinista, basado en nombre)".into(),
            uuid_random: "Aleatorio (nuevo UUID cada vez)".into(),
            worlds_title: "Mundos".into(),
            rename_world: "Renombrar mundo".into(),
            delete_world: "Eliminar mundo".into(),
            export_world: "Exportar mundo (zip)".into(),
            open_saves_folder: "Abrir carpeta de guardados".into(),
            world_new_name: "Nuevo nombre".into(),
            world_delete_confirm: "Eliminar permanentemente".into(),
            world_export_path: "Guardar zip en ruta".into(),
            no_versions_installed: "No hay versiones instaladas. Instala una primero.".into(),
            no_accounts_configured: "No hay cuentas configuradas.".into(),
            skin_requires_microsoft: "La gestión de skins requiere una cuenta de Microsoft.".into(),
            low_ram_warning: "RAM baja: el perfil necesita {}MB pero solo hay {}MB libres.".into(),
        }
    }

    pub fn french() -> Self {
        Self {
            code: "fr".into(), name: "Français".into(),
            menu_install_version: "Installer une version".into(),
            menu_install_mod_loader: "Installer un chargeur de mods".into(),
            menu_launch_game: "Lancer le jeu".into(),
            menu_launch_preset: "Lancer un profil".into(),
            menu_manage_presets: "Gérer les profils".into(),
            menu_manage_accounts: "Gérer les comptes".into(),
            menu_manage_textures: "Gérer les textures".into(),
            menu_manage_shaders: "Gérer les shaders".into(),
            menu_manage_instances: "Gérer les instances".into(),
            menu_manage_mods: "Gérer les mods".into(),
            menu_check_mod_updates: "Vérifier les mises à jour des mods".into(),
            menu_manage_skins: "Gérer les skins".into(),
            menu_manage_worlds: "Gérer les mondes".into(),
            menu_screenshot_gallery: "Galerie de captures".into(),
            menu_view_installed: "Voir les versions installées".into(),
            menu_launch_history: "Historique des lancements".into(),
            menu_news: "Actualités".into(),
            menu_exit: "Quitter".into(),
            back: "Retour".into(),
            yes: "Oui".into(),
            no: "Non".into(),
            confirm: "Confirmer".into(),
            select_account: "Sélectionner un compte".into(),
            select_version: "Sélectionner une version".into(),
            username: "Nom d'utilisateur".into(),
            password: "Mot de passe".into(),
            goodbye: "Au revoir.".into(),
            fetching_manifest: "Récupération du manifeste...".into(),
            downloading_jar: "Téléchargement du JAR client...".into(),
            downloading_libs: "Téléchargement des bibliothèques...".into(),
            downloading_assets: "Téléchargement des ressources...".into(),
            verifying_assets: "Vérification des ressources...".into(),
            validating_session: "Validation de la session...".into(),
            session_expired: "expirée".into(),
            session_refreshing: "Token expiré — actualisation...".into(),
            installed_ok: "installé avec succès !".into(),
            game_exited: "Le jeu s'est terminé avec le statut :".into(),
            add_local_profile: "Ajouter un profil local".into(),
            rename_local_profile: "Renommer un profil local".into(),
            remove_local_profile: "Supprimer un profil local".into(),
            login_microsoft: "Se connecter avec Microsoft".into(),
            refresh_microsoft: "Actualiser le token Microsoft".into(),
            remove_microsoft: "Supprimer le compte Microsoft".into(),
            uuid_type_prompt: "Type d'UUID".into(),
            uuid_offline: "Hors ligne (déterministe, basé sur le nom)".into(),
            uuid_random: "Aléatoire (nouvel UUID à chaque fois)".into(),
            worlds_title: "Mondes".into(),
            rename_world: "Renommer le monde".into(),
            delete_world: "Supprimer le monde".into(),
            export_world: "Exporter le monde (zip)".into(),
            open_saves_folder: "Ouvrir le dossier des sauvegardes".into(),
            world_new_name: "Nouveau nom".into(),
            world_delete_confirm: "Supprimer définitivement".into(),
            world_export_path: "Enregistrer le zip dans".into(),
            no_versions_installed: "Aucune version installée. Installez-en une d'abord.".into(),
            no_accounts_configured: "Aucun compte configuré.".into(),
            skin_requires_microsoft: "La gestion des skins nécessite un compte Microsoft.".into(),
            low_ram_warning: "RAM faible : le profil nécessite {}Mo mais seulement {}Mo sont libres.".into(),
        }
    }

    pub fn german() -> Self {
        Self {
            code: "de".into(), name: "Deutsch".into(),
            menu_install_version: "Version installieren".into(),
            menu_install_mod_loader: "Mod-Loader installieren".into(),
            menu_launch_game: "Spiel starten".into(),
            menu_launch_preset: "Profil starten".into(),
            menu_manage_presets: "Profile verwalten".into(),
            menu_manage_accounts: "Konten verwalten".into(),
            menu_manage_textures: "Texturen verwalten".into(),
            menu_manage_shaders: "Shader verwalten".into(),
            menu_manage_instances: "Instanzen verwalten".into(),
            menu_manage_mods: "Mods verwalten".into(),
            menu_check_mod_updates: "Mod-Updates prüfen".into(),
            menu_manage_skins: "Skins verwalten".into(),
            menu_manage_worlds: "Welten verwalten".into(),
            menu_screenshot_gallery: "Screenshot-Galerie".into(),
            menu_view_installed: "Installierte Versionen anzeigen".into(),
            menu_launch_history: "Startverlauf".into(),
            menu_news: "Neuigkeiten".into(),
            menu_exit: "Beenden".into(),
            back: "Zurück".into(),
            yes: "Ja".into(),
            no: "Nein".into(),
            confirm: "Bestätigen".into(),
            select_account: "Konto auswählen".into(),
            select_version: "Version auswählen".into(),
            username: "Benutzername".into(),
            password: "Passwort".into(),
            goodbye: "Auf Wiedersehen.".into(),
            fetching_manifest: "Versionsmanifest wird abgerufen...".into(),
            downloading_jar: "Client-JAR wird heruntergeladen...".into(),
            downloading_libs: "Bibliotheken werden heruntergeladen...".into(),
            downloading_assets: "Assets werden heruntergeladen...".into(),
            verifying_assets: "Assets werden überprüft...".into(),
            validating_session: "Sitzung wird validiert...".into(),
            session_expired: "abgelaufen".into(),
            session_refreshing: "Token abgelaufen — wird erneuert...".into(),
            installed_ok: "erfolgreich installiert!".into(),
            game_exited: "Spiel beendet mit Status:".into(),
            add_local_profile: "Lokales Profil hinzufügen".into(),
            rename_local_profile: "Lokales Profil umbenennen".into(),
            remove_local_profile: "Lokales Profil entfernen".into(),
            login_microsoft: "Mit Microsoft anmelden".into(),
            refresh_microsoft: "Microsoft-Token erneuern".into(),
            remove_microsoft: "Microsoft-Konto entfernen".into(),
            uuid_type_prompt: "UUID-Typ".into(),
            uuid_offline: "Offline (deterministisch, basierend auf Name)".into(),
            uuid_random: "Zufällig (neue UUID jedes Mal)".into(),
            worlds_title: "Welten".into(),
            rename_world: "Welt umbenennen".into(),
            delete_world: "Welt löschen".into(),
            export_world: "Welt exportieren (zip)".into(),
            open_saves_folder: "Speicherordner öffnen".into(),
            world_new_name: "Neuer Name".into(),
            world_delete_confirm: "Dauerhaft löschen".into(),
            world_export_path: "Zip speichern unter".into(),
            no_versions_installed: "Keine Versionen installiert. Bitte zuerst eine installieren.".into(),
            no_accounts_configured: "Keine Konten konfiguriert.".into(),
            skin_requires_microsoft: "Skin-Verwaltung erfordert ein Microsoft-Konto.".into(),
            low_ram_warning: "Wenig RAM: Profil benötigt {}MB, aber nur {}MB sind frei.".into(),
        }
    }

    pub fn russian() -> Self {
        Self {
            code: "ru".into(), name: "Русский".into(),
            menu_install_version: "Установить версию".into(),
            menu_install_mod_loader: "Установить загрузчик модов".into(),
            menu_launch_game: "Запустить игру".into(),
            menu_launch_preset: "Запустить профиль".into(),
            menu_manage_presets: "Управление профилями".into(),
            menu_manage_accounts: "Управление аккаунтами".into(),
            menu_manage_textures: "Управление текстурами".into(),
            menu_manage_shaders: "Управление шейдерами".into(),
            menu_manage_instances: "Управление экземплярами".into(),
            menu_manage_mods: "Управление модами".into(),
            menu_check_mod_updates: "Проверить обновления модов".into(),
            menu_manage_skins: "Управление скинами".into(),
            menu_manage_worlds: "Управление мирами".into(),
            menu_screenshot_gallery: "Галерея скриншотов".into(),
            menu_view_installed: "Просмотр установленных версий".into(),
            menu_launch_history: "История запусков".into(),
            menu_news: "Новости".into(),
            menu_exit: "Выход".into(),
            back: "Назад".into(),
            yes: "Да".into(),
            no: "Нет".into(),
            confirm: "Подтвердить".into(),
            select_account: "Выбрать аккаунт".into(),
            select_version: "Выбрать версию".into(),
            username: "Имя пользователя".into(),
            password: "Пароль".into(),
            goodbye: "До свидания.".into(),
            fetching_manifest: "Получение манифеста версий...".into(),
            downloading_jar: "Загрузка клиентского JAR...".into(),
            downloading_libs: "Загрузка библиотек...".into(),
            downloading_assets: "Загрузка ресурсов...".into(),
            verifying_assets: "Проверка ресурсов...".into(),
            validating_session: "Проверка сессии...".into(),
            session_expired: "истекла".into(),
            session_refreshing: "Токен истёк — обновление...".into(),
            installed_ok: "успешно установлено!".into(),
            game_exited: "Игра завершилась со статусом:".into(),
            add_local_profile: "Добавить локальный профиль".into(),
            rename_local_profile: "Переименовать локальный профиль".into(),
            remove_local_profile: "Удалить локальный профиль".into(),
            login_microsoft: "Войти через Microsoft".into(),
            refresh_microsoft: "Обновить токен Microsoft".into(),
            remove_microsoft: "Удалить аккаунт Microsoft".into(),
            uuid_type_prompt: "Тип UUID".into(),
            uuid_offline: "Оффлайн (детерминированный, по имени)".into(),
            uuid_random: "Случайный (новый UUID каждый раз)".into(),
            worlds_title: "Миры".into(),
            rename_world: "Переименовать мир".into(),
            delete_world: "Удалить мир".into(),
            export_world: "Экспортировать мир (zip)".into(),
            open_saves_folder: "Открыть папку сохранений".into(),
            world_new_name: "Новое имя".into(),
            world_delete_confirm: "Удалить навсегда".into(),
            world_export_path: "Сохранить zip по пути".into(),
            no_versions_installed: "Версии не установлены. Сначала установите версию.".into(),
            no_accounts_configured: "Аккаунты не настроены.".into(),
            skin_requires_microsoft: "Управление скинами требует аккаунт Microsoft.".into(),
            low_ram_warning: "Мало RAM: профиль требует {}МБ, но доступно только {}МБ.".into(),
        }
    }

    pub fn chinese() -> Self {
        Self {
            code: "zh".into(), name: "中文(简体)".into(),
            menu_install_version: "安装版本".into(),
            menu_install_mod_loader: "安装模组加载器".into(),
            menu_launch_game: "启动游戏".into(),
            menu_launch_preset: "启动预设".into(),
            menu_manage_presets: "管理预设".into(),
            menu_manage_accounts: "管理账户".into(),
            menu_manage_textures: "管理材质包".into(),
            menu_manage_shaders: "管理光影".into(),
            menu_manage_instances: "管理实例".into(),
            menu_manage_mods: "管理模组".into(),
            menu_check_mod_updates: "检查模组更新".into(),
            menu_manage_skins: "管理皮肤".into(),
            menu_manage_worlds: "管理存档".into(),
            menu_screenshot_gallery: "截图库".into(),
            menu_view_installed: "查看已安装版本".into(),
            menu_launch_history: "启动历史".into(),
            menu_news: "新闻".into(),
            menu_exit: "退出".into(),
            back: "返回".into(),
            yes: "是".into(),
            no: "否".into(),
            confirm: "确认".into(),
            select_account: "选择账户".into(),
            select_version: "选择版本".into(),
            username: "用户名".into(),
            password: "密码".into(),
            goodbye: "再见。".into(),
            fetching_manifest: "正在获取版本清单...".into(),
            downloading_jar: "正在下载客户端 JAR...".into(),
            downloading_libs: "正在下载库文件...".into(),
            downloading_assets: "正在下载资源...".into(),
            verifying_assets: "正在验证资源...".into(),
            validating_session: "正在验证会话...".into(),
            session_expired: "已过期".into(),
            session_refreshing: "令牌已过期 — 正在刷新...".into(),
            installed_ok: "安装成功！".into(),
            game_exited: "游戏退出，状态：".into(),
            add_local_profile: "添加本地档案".into(),
            rename_local_profile: "重命名本地档案".into(),
            remove_local_profile: "删除本地档案".into(),
            login_microsoft: "使用 Microsoft 登录".into(),
            refresh_microsoft: "刷新 Microsoft 令牌".into(),
            remove_microsoft: "删除 Microsoft 账户".into(),
            uuid_type_prompt: "UUID 类型".into(),
            uuid_offline: "离线（基于用户名的确定性 UUID）".into(),
            uuid_random: "随机（每次生成新 UUID）".into(),
            worlds_title: "存档".into(),
            rename_world: "重命名存档".into(),
            delete_world: "删除存档".into(),
            export_world: "导出存档 (zip)".into(),
            open_saves_folder: "打开存档文件夹".into(),
            world_new_name: "新名称".into(),
            world_delete_confirm: "永久删除".into(),
            world_export_path: "保存 zip 到路径".into(),
            no_versions_installed: "未安装任何版本，请先安装。".into(),
            no_accounts_configured: "未配置任何账户。".into(),
            skin_requires_microsoft: "皮肤管理需要 Microsoft 账户。".into(),
            low_ram_warning: "内存不足：配置需要 {}MB，但仅有 {}MB 可用。".into(),
        }
    }

    pub fn all() -> Vec<Self> {
        vec![
            Self::english(),
            Self::spanish(),
            Self::french(),
            Self::german(),
            Self::russian(),
            Self::chinese(),
        ]
    }

    pub fn by_code(code: &str) -> Self {
        Self::all().into_iter().find(|l| l.code == code).unwrap_or_else(Self::english)
    }
}

#[derive(Serialize, Deserialize)]
struct LangConfig { code: String }

pub fn lang_config_path(data_dir: &Path) -> std::path::PathBuf {
    data_dir.join("config").join("lang.json")
}

pub fn load_lang(data_dir: &Path) -> Lang {
    let path = lang_config_path(data_dir);
    std::fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str::<LangConfig>(&s).ok())
        .map(|c| Lang::by_code(&c.code))
        .unwrap_or_else(Lang::english)
}

pub fn save_lang(data_dir: &Path, code: &str) -> Result<()> {
    let path = lang_config_path(data_dir);
    if let Some(p) = path.parent() { std::fs::create_dir_all(p)?; }
    std::fs::write(path, serde_json::to_string(&LangConfig { code: code.into() })?)?;
    Ok(())
}
